name: GIT SYNC

on: [ push, delete, pull_request_target, label ]

jobs:
  git-sync:
    if: github.repository == 'littlejiancc/erda' && (github.event_name == 'push' ||  github.event_name == 'delete')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: unshallow
        run: git fetch --unshallow origin
      - name: add remote
        run: git remote add mirror https://${{ secrets.ERDA_CLOUD_MIRROR_GIT_USERNAME }}:${{ secrets.ERDA_CLOUD_MIRROR_GIT_PASSWORD }}@erda.daily.terminus.io/erda/dop/wxjcc/erda
      - name: push
        run: git push --tags --force mirror "refs/remotes/origin/*:refs/heads/*"
  git-sync-pr:
    if: github.repository == 'littlejiancc/erda' && (github.event_name == 'pull_request_target' ||  github.event_name == 'label') 
    runs-on: ubuntu-latest
    steps:
      - name: list open pull requests in last 24 hours
        id: list
        uses: andrea-armstrong/github-list-pull-requests@v1.0.0
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          state: 'open'
          window: '24'
      - uses: actions/checkout@v2
      - name: unshallow
        run: |
          git fetch --unshallow origin
          ss=${{ steps.list.outputs.pullRequestNumbers }}
          ss=${ss:1:${#ss}-2}
          IFS=', ' read -r -a arr <<< "$ss"
          for id in ${arr[@]}
          do
          git fetch origin "refs/pull/${id}/head:refs/remotes/origin/feature/pr/${id}"
          done
      - name: add remote
        run: git remote add mirror https://${{ secrets.ERDA_CLOUD_MIRROR_GIT_USERNAME }}:${{ secrets.ERDA_CLOUD_MIRROR_GIT_PASSWORD }}@erda.daily.terminus.io/erda/dop/wxjcc/erda
      - name: push
        run: git push --tags --force mirror "refs/remotes/origin/*:refs/heads/*"
