name: GIT SYNC

on: [ push, delete, pull_request ]

jobs:
  build:
    if: github.repository == 'littlejiancc/erda'
    runs-on: ubuntu-latest
    steps:
      - name: list open requests in last 24 hours
        id: list
        uses: andrea-armstrong/github-list-pull-requests@v1.0.0
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          state: 'open'
          window: '240'
      - name: output
        run: |
          ss=${{ steps.list.outputs.pullRequestNumbers }}
          ss=${ss:1:${#ss}-2}
          echo $ss
          IFS=', ' read -r -a arr <<< "$ss"
          for element in ${arr[@]}
          do
          echo $element
          done
      - uses: actions/checkout@v2
      - name: unshallow
        run: |
          git fetch --unshallow origin
          ss=${{ steps.list.outputs.pullRequestNumbers }}
          ss=${ss:1:${#ss}-2}
          IFS=', ' read -r -a arr <<< "$ss"
          for id in ${arr[@]}
          do
          git fetch origin 'refs/pull/$id/head:refs/remotes/origin/feature/pr/*'
          done
      - name: add remote
        run: git remote add mirror https://${{ secrets.ERDA_CLOUD_MIRROR_GIT_USERNAME }}:${{ secrets.ERDA_CLOUD_MIRROR_GIT_PASSWORD }}@erda.cloud/erda/dop/erda-project/erda
      - name: push
        run: git push --tags --force  mirror "refs/remotes/origin/*:refs/heads/*"
         
