name: GIT SYNC

on: [ push, delete, pull_request ]

jobs:
  build:
    if: github.repository == 'littlejiancc/erda'
    runs-on: ubuntu-latest
    steps:
      - name: list all closed pull requests in last 24 hours
        id: list
        uses: actions/github-list-pull-requests@v1.0
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          state: 'open'
          window: '24'
      - name: output
        run: echo '${{ steps.list.outputs.pullRequestNumbers }}
