name: GIT SYNC

on: [ push, delete, pull_request ]

jobs:
  build:
    if: github.repository == 'littlejiancc/erda'
    runs-on: ubuntu-latest
    steps:
      - name: list open requests in last 24 hours
        id: list
        uses: andrea-armstrong/github-list-pull-requests@v1.0.0
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          state: 'open'
          window: '240'
      - name: output
        run: echo '${{ steps.list.outputs.pullRequestNumbers }}'
